### ISSUE TITLE
belongsToMany associations

### ISSUE THREAD

**Issue by ofvera** [IIC2513-2019-1/syllabus#24]
He logrado realizar todas las asociaciones correspondientes, pero cuando tengo que realizar una N:N, sigo la guía de sequelize y me tira el siguiente error:
```
/Users/octavio/Documents/Universidad/2019/AppWeb/grupo-not-java/node_modules/sequelize/lib/associations/mixin.js:37
      throw new Error(this.name + '.belongsToMany called with something that\'s not a subclass of Sequelize.Model');
      ^

Error: recipe.belongsToMany called with something that's not a subclass of Sequelize.Model
    at Function.belongsToMany (/Users/octavio/Documents/Universidad/2019/AppWeb/grupo-not-java/node_modules/sequelize/lib/associations/mixin.js:37:13)
    at Function.recipe.associate (/Users/octavio/Documents/Universidad/2019/AppWeb/grupo-not-java/src/models/recipe.js:12:12)
...........
```

En el modelo recipe.js existe la siguiente asociación:
```
    recipe.belongsToMany(models.tools, {
      as: 'tools',
      through: 'recipeTool',
    });
```

Donde `tools` es un modelo y `recipeTool` también es un modelo, por lo que no entiendo por qué dice no ser un 'subclass of Sequelize.Model'.

**Comment by ofvera** [comment]
`syntax error` era `models.tool`
